import sympy as sp
from sympy.utilities.lambdify import lambdastr

def generate_area_massflow_mach_relations(f):
    # use sympy to create python functions for area and mass flow rate
    A, mdot, rho_0, T_0, gamma, c_p, M = sp.symbols('A, dm, rho_0, T_0, gamma, c_p, M')

    area_relation_rhs = mdot/rho_0 * (1 + (gamma-1)/2*M**2)**(1/(gamma-1)) * (2*c_p*T_0*(1-1/(1+(gamma-1)/2*M**2)))**-0.5

    area_imp_str = lambdastr([M, mdot, rho_0, T_0, c_p, gamma], area_relation_rhs)

    area_relation = sp.Eq(A, area_relation_rhs)
    massflow_relation_rhs = sp.solve(area_relation, mdot)[0]

    massflow_imp_str = lambdastr([M, A, rho_0, T_0, c_p, gamma], massflow_relation_rhs)

    f.write('area_imp=')
    f.write(area_imp_str)
    f.write('\n')
    f.write('massflow_imp=')
    f.write(massflow_imp_str)
    f.write('\n')

# https://www.grc.nasa.gov/www/k-12/airplane/normal.html
def generate_shock_relations(f):
    p_0u, gamma, M_u = sp.symbols('p_0u gamma M_u')

    p0d_of_gamma_rel = p_0u*((gamma+1)*M_u**2/((gamma-1)*M_u**2+2))**(gamma/(gamma-1))*((gamma+1)/(2*gamma*M_u**2-(gamma-1)))**(1/(gamma-1))

    postshock_p0_str = lambdastr([p_0u, M_u, gamma], p0d_of_gamma_rel)

    f.write('postshock_p0_impl=')
    f.write(postshock_p0_str)
    f.write('\n')

def generate_mach_relations(f):
    p_0, p, M, gamma = sp.symbols('p_0 p M gamma')

    p0_p_of_M_eq = sp.Eq(p_0/p, (1+(gamma-1)/2*M**2)**(gamma/(gamma-1)))
    p_of_M_eq = sp.solve(p0_p_of_M_eq, p)[0]
    M_of_p_eq = sp.solve(p0_p_of_M_eq, M)[1]

    p_of_M_eq_str = lambdastr([M, p_0, gamma], p_of_M_eq)
    M_of_p_eq_str = lambdastr([p, p_0, gamma], M_of_p_eq)

    f.write('mach_to_pres_impl=')
    f.write(p_of_M_eq_str)
    f.write('\n')
    f.write('pres_to_mach_impl=')
    f.write(M_of_p_eq_str)
    f.write('\n')

with open("relations.py", 'wt') as f:
    f.write('# This file is automatically generated. Please do not edit.\n')
    f.write('from numpy import sqrt\n')

    generate_area_massflow_mach_relations(f)
    generate_shock_relations(f)
    generate_mach_relations(f)
